---
title = "Обзор книги «Сигнал и Шум»"
external_url = "https://tiendil.org/ru/posts/review-of-the-signal-and-the-noise"
external_tags = []
published_at = "2024-07-16T12:00:00+00:00"
---
<figure class="brigid-images brigid-images-1">



  <a href="https://tiendil.org/static/posts/review-of-the-signal-and-the-noise/cover_ru.jpg"
     class="brigid-image-link"
     data-pswp-width="1439"
     data-pswp-height="2000"
     target="_blank">
     <img src="https://tiendil.org/static/posts/review-of-the-signal-and-the-noise/cover_ru.jpg" alt="Обложка книги «Сигнал и Шум»." />
  </a>


</figure>
<p><a href="https://en.wikipedia.org/wiki/Nate_Silver" target="_blank">Нейт Сильвер</a> — автор «Сигнала и Шума» — широко известен благодаря своим удачным прогнозам, например, выборов в США. Неудивительно, что книга стала бестселлером.</p>
<p>Собственно, прогнозам книга  и посвящена: подходам к прогнозированию, сложностям, ошибкам, заблуждениям и так далее.</p>
<p>Как обычно, я рассчитывал на более теоретическое изложение, в духе <a href="https://tiendil.org/ru/posts/scale">Масштаба</a>, но автор выбрал другой путь и подаёт свои идеи через разбор конкретных случаев: один случай на главу. Каждая глава описывает большую задачу, например, предсказание погоды, и с помощью неё даёт несколько призм для взгляда на прогнозирование. Это определённо делает материал доступнее, но лично я хотел бы больше системности и теории.</p>
<p>Из-за подхода через изложение кейсов, сделать краткую выдержку из книги сложно. Это возможно, было бы даже интересно попробовать, но объём работы слишком большой — автор не ставил целью свести всё в цельную систему или короткий набор тезисов.</p>
<p>Поэтому дам отзыв на книгу в целом, примерный перечень призм и набор прикольных фактов.</p>
