---
title = "Генерация подземелий — от простого к сложному"
external_url = "https://tiendil.org/ru/posts/dungeon-generation-from-simple-to-complex"
external_tags = []
published_at = "2020-04-16T12:00:00+00:00"
---
      <figure class="brigid-images brigid-images-1">



  <a href="https://tiendil.org/static/posts/dungeon-generation-from-simple-to-complex/images/cover.png" class="brigid-image-link" data-pswp-width="640" data-pswp-height="494" target="_blank">
     <img src="https://tiendil.org/static/posts/dungeon-generation-from-simple-to-complex/images/cover.png" alt="Что у нас должно получиться.">
  </a>


  <figcaption><p>Что у нас должно получиться.</p></figcaption>
</figure>
<p>В этом уроке рассказывается, как запрограммировать подземелье. Если вы не программист, вам будет интересно почитать <a href="https://tiendil.org/ru/posts/how-to-design-a-dungeon">как придумать подземелье</a>.</p>
<p>Несколько вечеров проверял идею генерации космических баз. Космическая база в итоге не получилась, а вот на добротное подземелье результат похож. Поскольку шёл от простого к сложному и никакой суровой магии не делал, то решил переработать код в урок по генерации подземелий на Python.</p>
<p>В итоге у нас получится генератор подземелий со следующими свойствами:</p>
<ul>
<li>Комнаты будут соединены коридорами.</li>
<li>Топологически подземелье будет иметь форму <a href="https://ru.wikipedia.org/wiki/%D0%94%D0%B5%D1%80%D0%B5%D0%B2%D0%BE_(%D1%82%D0%B5%D0%BE%D1%80%D0%B8%D1%8F_%D0%B3%D1%80%D0%B0%D1%84%D0%BE%D0%B2)" target="_blank">дерева</a>. Добавить циклы будет элементарно, но уже в качестве домашнего задания.</li>
<li>Будет настраиваться количество комнат, их размер, «уровень ветвления».</li>
<li>Подземелье будет располагаться на клеточной сетке (состоять из квадратных клеток).</li>
</ul>
<p>Весь код можно найти на <a href="https://github.com/Tiendil/tutorial-dungeon-generation" target="_blank">github</a>.</p>
<p>Кода в посте не будет — все используемые подходы легко описываются словами.</p>
<p><strong>Для каждого этапа разработки в репозитории будет создан отдельный тэг, содержащий код на момент завершения этапа.</strong></p>
<p>Задача этого урока не столько научить программировать генераторы подземелий, сколько показать, что кажущиеся сложными вещи на деле довольно просты, если их правильно разбить на подзадачи.</p>
