---
title = "First person step on Mars in 2030 according to Musk"
external_url = "https://some-news.example.com/first-person-step-on-mars-in-2030-according-to-musk"
external_tags = []
published_at = "2024-08-16T12:00:00+00:00"
---
