id = "09887b50-48b0-420a-b614-772e85617cb7"
gui_order = 1
name = "Feeds Fun"
description = "News of our project and related topics."

[[feeds]]
  url = "https://blog.feeds.fun/en/feeds/atom"
  title = "Feeds Fun Blog"
  description = "News and documentation of the Feeds Fun project"

[[feeds]]
  url = "https://www.reddit.com/r/feedsfun/.rss"
  title = "Feeds Fun Subreddit"
  description = "News, community discussions and feedback for the Feeds Fun project"
