tags_must_have = [
  'book-reviews',
  'forecasting',
  'nate-silver',
  'signal-and-noise',
]
tags_should_have = [
  'statistics',
  'analysis',
  'analytical-methods',
  'analytical-techniques',
  'analytics',
  'approaches-to-forecasting',
  'bestseller',
  'bestsellers',
  'bestselling-authors',
  'bestselling-books',
  'book-review',
  'books',
  'case-analysis',
  'case-studies',
  'case-study',
  'climate-change',
  'climate-science',
  'cognitive-bias',
  'complex-systems',
  'complexities-in-forecasting',
  'complexity',
  'critical-thinking',
  'data-analysis',
  'data-driven-decision-making',
  'data-driven-decisions',
  'data-interpretation',
  'data-science',
  'decision-making',
  'economic-forecasting',
  'economics',
  'election-predictions',
  'elections',
  'errors',
  'errors-in-forecasting',
  'evidence-based-decision-making',
  'forecast-errors',
  'forecasting-accuracy',
  'forecasting-approaches',
  'forecasting-challenges',
  'forecasting-errors',
  'forecasting-impacts',
  'forecasting-issues',
  'forecasting-methodologies',
  'forecasting-methods',
  'forecasting-practices',
  'forecasting-techniques',
  'market-trends',
  'meteorology',
  'misconceptions',
  'misconceptions-in-forecasting',
  'model-comparison',
  'model-evaluation',
  'political-forecasting',
  'practical-application',
  'practical-approaches',
  'practical-examples',
  'prediction',
  'predictive-analytics',
  'predictive-modeling',
  'public-opinion',
  'real-world-applications',
  'risk-analysis',
  'risk-management',
  'scale',
  'statistical-analysis',
  'statistical-forecasting',
  'statistical-inference',
  'statistical-methods',
  'statistical-modeling',
  'statistical-significance',
  'statistical-theory',
  'strategic-planning',
  'successful-forecasts',
  'system-dynamics',
  'uncertainty',
  'united-states-elections',
  'us-elections',
  'weather',
  'weather-forecast',
  'weather-forecasting',
  'weather-prediction']
