tags_must_have = [
  'dungeon-generation',
  'game-development',
  'github',
  'python',
  'tutorials',
]
tags_should_have = [
  'agile-development',
  'algorithm',
  'algorithm-design',
  'algorithm-development',
  'algorithm-implementation',
  'algorithm-repositories',
  'algorithmic-design',
  'code',
  'code-repository',
  'code-sample',
  'complexity',
  'complexity-in-design',
  'complexity-management',
  'complexity-reduction',
  'corridor-connection',
  'corridor-design',
  'corridor-layout',
  'data-structures',
  'data-visualization',
  'design-and-implementation',
  'design-iteration',
  'design-thinking',
  'development',
  'development-methodologies',
  'digital-creation',
  'digital-game-development',
  'dungeon',
  'dungeon-design',
  'dungeon-generator',
  'education',
  'educational-content',
  'game-architecture',
  'game-design',
  'game-design-education',
  'game-development-education',
  'game-development-process',
  'game-development-techniques',
  'game-prototyping',
  'gamedev',
  'graph-algorithms',
  'graph-theory',
  'grid-based-design',
  'grid-layout',
  'guide',
  'knowledge-sharing',
  'level-design',
  'level-generation',
  'open-source',
  'open-source-projects',
  'open-source-software',
  'practice',
  'procedural-content-generation',
  'procedural-generation',
  'programming',
  'programming-education',
  'programming-languages',
  'programming-tutorials',
  'python-programming',
  'repository',
  'room-configuration',
  'room-connection',
  'room-creation',
  'room-layout',
  'software',
  'software-architecture',
  'software-design',
  'software-development',
  'software-development-education',
  'software-engineering',
  'step-by-step-instruction',
  'system-architecture',
  'system-design',
  'tutorial',
  'tutorial-dungeon-generation',
  'tutorial-repositories',
  'tutorials-and-guides',
  'user-experience',
  'user-experience-design']
