tags_must_have = [
  'anrich-nortje',
  'axar-patel',
  'cricket',
  'hardik-pandya',
  'heinrich-klaasen',
  'india',
  'jasprit-bumrah',
  'kensington-oval',
  'keshav-maharaj',
  'quinton-de-kock',
  'rohit-sharma',
  'south-africa',
  'sports',
  'tristan-stubbs',
  'virat-kohli',
]

tags_should_have = [
  'athlete-development',
  'athlete-nutrition',
  'athlete-performance',
  'athletic-achievements',
  'athletic-competitions',
  'athletic-training',
  'athletics',
  'barbados',
  'barbados-sports',
  'batting',
  'batting-performance',
  'batting-stats',
  'bowling',
  'bowling-performance',
  'bowling-stats',
  'coaching',
  'competitive-sports',
  'cricket-analytics',
  'cricket-players',
  'cricket-rivalries',
  'cricket-sponsorship',
  'cricket-statistics',
  'cricket-tactics',
  'cricket-west-indies',
  'cricket-world-cup',
  'global-competitions',
  'global-events',
  'global-sports',
  'global-sports-events',
  'international-competitions',
  'international-cricket',
  'international-sports',
  'international-sports-events',
  'match-analysis',
  'match-highlights',
  'match-results',
  'match-strategy',
  'match-tactics',
  'performance-analysis',
  'performance-evaluation',
  'player-awards',
  'player-development',
  'player-injuries',
  'player-performance',
  'player-retirement',
  'player-statistics',
  'retirement',
  'south-africa-cricket',
  'sponsorship',
  'sponsorship-deals',
  'sports-administration',
  'sports-analytics',
  'sports-coaching',
  'sports-journalism',
  'sports-statistics',
  'sports-strategy',
  't20-format',
  't20-world-cup',
  'team-dynamics',
  'team-sports',
  'tournament',
  'tournaments',
  'umpiring-decisions',
  'usa-cricket',
  'world-cup',
]
