tags_must_have = [
  'aiden-bowden',
  'cannock-chase-district',
  'chase-pride',
  'community-events',
  'cultural-diversity',
  'england',
  'event-management',
  'event-planning',
  'facebook',
  'friends-of-hednesford-park',
  'hednesford',
  'instagram',
  'josh-newbury',
  'lgbtq-pride',
  'lgbtq-rights',
  'local-celebrations',
  'local-government',
  'local-history',
  'local-initiatives',
  'nonprofit-organizations',
  'pride-festivals',
  'sage-charity',
  'social-issues',
  'staffordshire',
]

tags_should_have = [
  'activism',
  'advocacy',
  'advocacy-and-activism',
  'advocacy-for-equality',
  # 'aiden-bowden',
  'arts-and-culture',
  'ash-thawley',
  'cannock-chase',
  # 'cannock-chase-district',
  'charitable-organizations',
  'charity-support',
  # 'chase-pride',
  'civic-engagement',
  'civic-leadership',
  'communications',
  'community-activism',
  'community-activities',
  'community-and-culture',
  'community-building',
  'community-development',
  'community-engagement',
  # 'community-events',
  'community-feedback',
  'community-festivals',
  'community-initiatives',
  'community-meetings',
  'community-partnerships',
  'community-solidarity',
  'community-support',
  'community-sustainability',
  'council-of-queers',
  'cultural-activism',
  'cultural-advocacy',
  # 'cultural-diversity',
  'cultural-diversity-promotion',
  'cultural-festivals',
  'cultural-identity',
  'cultural-initiatives',
  'diversity-and-inclusion',
  'economic-challenges',
  'economics',
  'education',
  # 'england',
  # 'event-management',
  'event-management-industry',
  'event-marketing',
  'event-marketing-strategies',
  'event-organization',
  'event-participation',
  # 'event-planning',
  'event-planning-and-management',
  'event-planning-and-organization',
  'event-planning-challenges',
  'event-sustainability',
  # 'facebook',
  'family-craft-workshop',
  'family-craft-workshops',
  'family-workshops',
  # 'friends-of-hednesford-park',
  'funding-and-grants',
  'funding-and-resources',
  'funding-challenges',
  'funding-issues',
  'funding-sources',
  'fundraising',
  'fundraising-strategies',
  'gender-studies',
  'government-and-legislation',
  'government-legislation',
  'government-policy',
  'government-relations',
  'grant-writing',
  # 'hednesford',
  'hednesford-town',
  'historical-context',
  'human-resources',
  'humanities',
  'identity-and-diversity',
  'identity-politics',
  # 'instagram',
  'intersectionality',
  # 'josh-newbury',
  'kathryn-downs',
  'law-and-policy',
  'lgbtq-activism',
  'lgbtq-history',
  # 'lgbtq-pride',
  # 'lgbtq-rights',
  'local-activism',
  'local-advocacy',
  'local-arts',
  'local-business-support',
  # 'local-celebrations',
  'local-charities',
  'local-charity',
  'local-culture',
  'local-economy',
  'local-funding-sources',
  'local-governance',
  # 'local-government',
  'local-government-funding',
  'local-heritage',
  # 'local-history',
  'local-history-and-heritage',
  'local-history-promotion',
  # 'local-initiatives',
  'local-initiatives-funding',
  'local-lgbtq-charity',
  'local-mp',
  'local-mp-engagement',
  'local-pride-events',
  'media-and-communication',
  'media-and-communications',
  'media-relations',
  'mini-chase-pride',
  'networking',
  'networking-and-collaboration',
  'nonprofit-management',
  # 'nonprofit-organizations',
  'nonprofit-sector',
  'policy-advocacy',
  'pride-event-planning',
  'pride-events',
  # 'pride-festivals',
  'pride-flag-displays',
  'pride-flags',
  'pride-history',
  # 'sage-charity',
  'social-acceptance',
  'social-acceptance-issues',
  'social-advocacy',
  'social-change',
  'social-entrepreneurship',
  'social-innovation',
  # 'social-issues',
  'social-issues-and-advocacy',
  'social-issues-awareness',
  'social-justice',
  'social-justice-domain',
  'social-justice-initiatives',
  'social-media-and-communication',
  'social-media-engagement',
  'social-media-marketing',
  'social-movements',
  'social-responsibility',
  'social-services',
  'social-work',
  # 'staffordshire',
  'stakeholder-engagement',
  'sustainability',
  'uk-shared-prosperity-fund',
  'urban-planning',
  'volunteer-management',
  'volunteerism',
  'youth-development',
  'youth-engagement',
  'youth-engagement-programs',
  'youth-services'
]
