tags_must_have = [
  "aerospace",
  "aerospace-engineering",
  "aerospace-industry",
  "astronauts",
  "barry-wilmore",
  "boeing",
  "boeing-starliner",
  "commercial-crew-program",
  "commercial-spaceflight",
  "crew-8",
  "crew-9",
  "crew-dragon",
  "expedition-71-72",
  "helium-leaks",
  "human-spaceflight",
  "launch-operations",
  "nasa",
  "space-agencies",
  "space-announcements",
  "space-exploration",
  "space-innovation",
  "space-logistics",
  "space-mission-architecture",
  "space-mission-scheduling",
  "space-missions",
  "space-news",
  "space-safety",
  "space-technology",
  "spacecraft",
  "spacecraft-safety",
  "spacex",
  "steve-stich",
  "sunita-williams",
  "thruster-malfunctions",]

tags_should_have = [
  "astronauts-return",
  "aviation-safety",
  "crew-9-planning",
  "crew-transport",
  "government-contracting",
  "mission-operations",
  "mission-planning",
  "national-public-radio",
  "new-mexico",
  "robotics",
  "space-agency-collaboration",
  "space-engineering",
  "space-entrepreneurship",
  "space-exploration-initiatives",
  "space-infrastructure",
  "space-mission-analytics",
  "space-mission-failures",
  "space-operations",
  "space-reports",
  "space-safety-standards",
  "space-systems-engineering",
  "space-transportation",
  "space-transportation-systems",
  "spacecraft-certification",
  "spacecraft-landing-plans",
  "spacecraft-operations",
  "spacecraft-reliability",
  "spacecraft-technology",
  "spaceflight-history",
  "spacesuit-designs",
]
