tags_must_have = [
  "api-development",
  "api-key-management",
  "api-keys",
  "application-development",
  "artificial-intelligence",
  "bug-reporting",
  "code-quality",
  "code-reviews",
  "development-practices",
  "feeds-fun",
  "gemini",
  "github",
  "haystack",
  "information-technology",
  "integration-bugs",
  "langchain",
  "langchain-ai",
  "llamaindex",
  "llm-frameworks",
  "machine-learning",
  "multi-tenant-applications",
  "multi-tenant-architecture",
  "production-readiness",
  "python",
  "quality-assurance",
  "security-issues",
  "singleton",
  "singleton-pattern",
  "software-architecture",
  "software-development",
  "software-engineering",
  "software-reliability",
  "software-security",
  "software-testing",
  "system-architecture",
  "system-integration",
  "user-experience",
]

tags_should_have = [
  "api",
  "api-client-implementation",
  "api-integration",
  "api-management",
  "api-security",
  "artificial-intelligence-development",
  "client-implementation",
  "client-server-architecture",
  "code-quality-control",
  "data-security",
  "development-methodologies",
  "development-challenges",
  "development-standards",
  "error-assessment",
  "error-handling",
  "gemini-integration",
  "google",
  "haystack-integration",
  "langchain-plugin",
  "llamaindex-bug",
  "open-source-development",
  "open-source-software",
  "production",
  "python-sdk",
  "security-engineering",
  "security-vulnerabilities",
  "software-bugs",
  "software-architecture-challenges",
  "software-architecture-design",
  "software-architecture-evaluation",
  "software-architecture-patterns",
  "software-architecture-principles",
  "software-ecosystem",
  "software-engineering-practices",
  "software-integration-challenges",
  "software-standards",
  "software-testing-methodologies",
  "system-design",
  "technology-trust",
  "user-data-privacy",
  "web-development",
]
