tags_must_have = [
  "attempted-assassination",
  "civil-rights",
  "cnn",
  "criminal-justice",
  "criminal-law",
  "department-of-justice",
  "donald-trump",
  "federal-charges",
  "florida",
  "government",
  "gun-violence",
  "law",
  "law-and-order",
  "law-enforcement",
  "merrick-garland",
  "nbc-news",
  "political-safety",
  "political-violence",
  "politics",
  "presidential-candidates",
  "public-officials",
  "public-policy",
  "public-safety",
  "ryan-wesley-routh",
  "trump-international-golf-club",
  "united-states",
  "west-palm-beach",
]

tags_should_have = [
  "arrest-procedures",
  "assassination-attempts",
  "assassination-plans",
  "case-law",
  "civil-liberties",
  "civil-rights-issues",
  "court-charges",
  "court-proceedings",
  "criminal-activity",
  "criminal-history",
  "criminal-intent",
  "criminal-justice-system",
  "criminal-prosecution",
  "evidence-collection",
  "fbi",
  "federal-bureau-of-investigation",
  "federal-investigations",
  "federal-prosecution",
  "firearm-possession",
  "firearm-usage",
  "golf",
  "government-agencies",
  "human-rights",
  "investigation",
  "investigative-techniques",
  "judicial-accountability",
  "judicial-system",
  "law-and-society",
  "law-enforcement-agencies",
  "legal-practice",
  "martin-county",
  "martin-county-sheriffs-office",
  "note-evidence",
  "political-activism",
  "political-assassination",
  "presidential-security",
  "public-officials-safety",
  "public-safety-policy",
  "security",
  "security-agencies",
  "trump-organization",
  "violence-in-politics",
  "violent-crime",
  "violent-offenses",
  "white-house",
]
