tags_must_have = [
  "brand-management",
  "content-creation",
  "cosplay",
  "cosplay-culture",
  "cultural-exchange",
  "cultural-identity",
  "cultural-phenomena",
  "dakimakura",
  "digital-culture",
  "digital-marketing",
  "entertainment",
  "entertainment-industry",
  "fan-culture",
  "graduation",
  "hololive",
  "hololive-production",
  "influencer-marketing",
  "internet-culture",
  "japan",
  "japanese-entertainment",
  "livestreams",
  "marketing",
  "media-production",
  "merchandise",
  "merchandising",
  "myth",
  "online-streaming",
  "popularization",
  "streaming-activities",
  "virtual-communities",
  "vtubers",
  "watson-amelia",
  "yahoo-japan",
]

tags_should_have = [
  "business-development",
  "celebrity-culture",
  "consumer-behavior",
  "content-development",
  "creative-industries",
  "cultural-globalization",
  "culture",
  "digital-communications",
  "digital-entrepreneurship",
  "digital-media",
  "generation",
  "globalization",
  "media-ecosystem",
  "october",
  "october-1",
  "online-communities",
  "online-fandoms",
  "september",
  "september-21",
  "september-30",
  "social-media-influencers",
  "solomon203",
  "streaming-platforms",
  "streaming-schedules",
  "taiwan",
  "taiwanese-cosplayer",
  "virtual-entertainment",
  "vtuber-communities",
  "vtuber-culture"
]
