tags_must_have = []
tags_should_have = [
  'aerospace',
  'aerospace-industry',
  'aerospace-innovation',
  'aerospace-technology',
  'astronauts',
  'colonization',
  'elon-musk',
  'elon-musk-statements',
  'engineering',
  'entrepreneurship',
  'exploration',
  'exploration-and-discovery',
  'exploration-of-mars',
  'extraterrestrial-colonization',
  'extraterrestrial-exploration',
  'future-of-humanity',
  'future-of-space',
  'future-of-technology',
  'future-predictions',
  'future-space-missions',
  'future-technology',
  'global-challenges',
  'global-space-initiatives',
  'habitat-construction',
  'healthcare-in-space',
  'human-adaptation-in-space',
  'human-adaptation-to-space',
  'human-ambition',
  'human-presence-on-mars',
  'human-resources-in-space',
  'human-space-exploration',
  'human-spaceflight',
  'human-spaceflight-programs',
  'humanity',
  'humanity-and-space',
  'humanity-in-space',
  'innovation',
  'innovation-and-technology',
  'international-cooperation',
  'international-space-law',
  'interplanetary-colonization',
  'interplanetary-human-missions',
  'interplanetary-human-travel',
  'interplanetary-travel',
  'interview',
  'launch-schedules',
  'life-support-systems',
  'mars',
  'mars-colonization',
  'mars-colony',
  'mars-environment',
  'mars-exploration-strategies',
  'mars-landing',
  'mars-mission-timeline',
  'mars-missions',
  'mars-surface-exploration',
  'mission-planning',
  'press-release',
  'private-aerospace-sector',
  'private-space-companies',
  'science',
  'scientific-advancement',
  'scientific-discovery',
  'scientific-research',
  'space-advocacy',
  'space-agencies',
  'space-ambitions',
  'space-colonization',
  'space-colonization-initiatives',
  'space-economics',
  'space-economy',
  'space-enthusiasm',
  'space-entrepreneurial-ecosystem',
  'space-entrepreneurship',
  'space-entrepreneurship-ecosystem',
  'space-entrepreneurship-initiatives',
  'space-exploration',
  'space-exploration-challenges',
  'space-exploration-future',
  'space-exploration-initiatives',
  'space-foundation',
  'space-industry',
  'space-industry-evolution',
  'space-infrastructure',
  'space-innovation',
  'space-innovation-and-research',
  'space-logistics',
  'space-mission-architecture',
  'space-mission-challenges',
  'space-mission-design',
  'space-mission-funding',
  'space-mission-operations',
  'space-mission-planning',
  'space-mission-timelines',
  'space-missions',
  'space-race',
  'space-race-history',
  'space-research',
  'space-research-funding',
  'space-science',
  'space-startups',
  'space-systems-engineering',
  'space-technology',
  'space-technology-advancements',
  'space-technology-ecosystem',
  'space-technology-innovation',
  'space-tourism',
  'space-transportation',
  'space-transportation-systems',
  'space-vision',
  'space-vision-and-aspirations',
  'spacecraft-design',
  'spacecraft-technology',
  'spacex',
  'systems-engineering',
  'technological-advancement',
  'technological-advancements',
  'technological-impacts',
  'technological-innovation',
  'technological-innovation-in-space',
  'technology',
  'technology-advancements',
  'technology-development',
  'transportation',
  'vision-for-space-exploration']
