# TODO: add evolution here
# TODO: add all named persons
# TODO: add memes, memeplexes
tags_must_have = [
  'memetics',
  'richard-dawkins',
]

tags_should_have = [
  'aaron-lynch',
  'anthropology',
  'behavioral-science',
  'charles-lumsden',
  'cognitive-ethology',
  'cognitive-evolution',
  'cognitive-memes',
  'cognitive-psychology',
  'cognitive-science',
  'communication',
  'communication-studies',
  'cultural-analyses',
  'cultural-analytics',
  'cultural-anthropology',
  'cultural-communication',
  'cultural-communication-theory',
  'cultural-competition',
  'cultural-constructs',
  'cultural-diffusion',
  'cultural-dynamics',
  'cultural-epistemology',
  'cultural-evolution',
  'cultural-evolutionary-theory',
  'cultural-formation',
  'cultural-heritage',
  'cultural-ideas',
  'cultural-interpretation',
  'cultural-knowledge',
  'cultural-memes',
  'cultural-memetics',
  'cultural-mutation',
  'cultural-narratives',
  'cultural-ontology',
  'cultural-phenomena',
  'cultural-phenomenology',
  'cultural-phenomenon',
  'cultural-replication',
  'cultural-replicator',
  'cultural-research',
  'cultural-rituals',
  'cultural-selection',
  'cultural-semiotics',
  'cultural-sociology',
  'cultural-structure',
  'cultural-structures',
  'cultural-studies',
  'cultural-symbols',
  'cultural-systems',
  'cultural-theory',
  'cultural-transmission',
  'cultural-unit',
  'cultural-variation',
  'dan-sperber',
  'daniel-dennett',
  'digital-culture',
  'ernst-mayr',
  'evolutionary-biology',
  'evolutionary-psychology',
  'evolutionary-theory',
  'george-c-williams',
  'imitation',
  'information-science',
  'information-theory',
  'information-transfer',
  'internet-communication',
  'internet-culture',
  'internet-meme',
  'internet-memes',
  'internet-phenomena',
  'jack-balkin',
  'john-tooby',
  'kalevi-kull',
  'kim-sterelny',
  'limor-shifman',
  'linguistics',
  'media-communication',
  'media-studies',
  'media-theory',
  'meme',
  'meme-analytics',
  'meme-communication',
  'meme-competition',
  'meme-critique',
  'meme-diffusion',
  'meme-inheritance',
  'meme-interpretation',
  'meme-mutation',
  'meme-propagation',
  'meme-replication',
  'meme-structures',
  'meme-theory',
  'meme-transmission',
  'meme-variation',
  'memeplex',
  'memeplexes',
  'memes',
  'memetic-theory',
  'memetics',
  'neuroscience',
  'pascal-boyer',
  'paul-griffiths',
  'philosophy',
  'political-memes',
  'political-science',
  'psychology',
  'religious-memes',
  'scott-atran',
  'semiotics',
  'social-memes',
  'social-psychology',
  'social-sciences',
  'social-theory',
  'sociocultural-evolution',
  'sociology',
  'susan-blackmore',
  'symbolic-meaning',
  'thomas-henry-huxley',
  'viral-marketing',
  'viral-memes',
  'viral-phenomenon']
