tags_must_have = [
  'bioinformatics',
  'cell-biology',
  'clinical-oncology',
  'glioblastoma-multiforme',
  'neuroscience',
  'virology',
  'zika-virus'
]

tags_should_have = [
  'adult-gbm',
  'biological-research',
  'biomarker-discovery',
  'biomedical-advancements',
  'biomedical-innovation',
  'biomedical-research',
  'biomedical-research-paper',
  'biomedical-sciences',
  'brain-cancer',
  'cancer-biology',
  'cancer-biology-research',
  'cancer-biomarkers',
  'cancer-cell-biology',
  'cancer-cell-death-mechanisms',
  'cancer-cell-infection',
  'cancer-cell-invasion',
  'cancer-cell-lines',
  'cancer-cell-regulation',
  'cancer-cell-research',
  'cancer-genetics',
  'cancer-genomics',
  'cancer-research',
  'cancer-research-methods',
  'cancer-therapeutics',
  'cancer-therapies',
  'cancer-therapy',
  'cancer-therapy-innovation',
  'cancer-therapy-research',
  'cancer-therapy-strategies',
  'cancer-treatment',
  'cell-line-experiments',
  'cell-line-validation',
  'clinical-applications',
  'clinical-research',
  'data-analysis',
  'differential-regulation',
  'dysregulated-genes',
  'experimental-medicine',
  'experimental-research',
  'functional-validation',
  'gene-dysregulation',
  'gene-expression',
  'gene-expression-analysis',
  'gene-expression-study',
  'gene-regulation',
  'genetic-engineering',
  'genetic-regulation',
  'genetic-research',
  'genomics',
  'healthcare-research',
  'long-non-coding-rna',
  'long-non-coding-rna-function',
  'long-non-coding-rnas',
  'medical-research',
  'medical-sciences',
  'meta-analysis',
  'molecular-analysis',
  'molecular-biology',
  'molecular-mechanisms',
  'molecular-medicine',
  'molecular-pathology',
  'molecular-research',
  'molecular-signaling',
  'molecular-signaling-pathways',
  'molecular-signaling-research',
  'molecular-signatures',
  'molecular-targeted-therapy',
  'molecular-targeting',
  'molecular-targets',
  'molecular-therapeutics',
  'neuro-oncology',
  'neuroblastoma',
  'nf-kappab',
  'oncology',
  'oncolytic-virotherapy',
  'p53',
  'p53-signaling-pathway',
  'pathology',
  'pathway-enrichment',
  'pediatric-gbm',
  'research-findings',
  'research-methodologies',
  'research-paper',
  'scientific-study',
  'therapeutic-advancements',
  'therapeutic-agents',
  'therapeutic-approaches',
  'therapeutic-biology',
  'therapeutic-development',
  'therapeutic-discovery',
  'therapeutic-efficacy',
  'therapeutic-implications',
  'therapeutic-innovation',
  'therapeutic-innovation-study',
  'therapeutic-potential',
  'therapeutic-research',
  'therapeutic-sciences',
  'therapeutic-strategies',
  'therapeutic-targets',
  'therapeutics',
  'transcriptomic-meta-analysis',
  'transcriptomics',
  'translational-research',
  'tumor-biology',
  'tumor-cell-death',
  'tumor-immunology',
  'tumor-necrosis-factor',
  'viral-infection-therapy',
  'viral-infections',
  'viral-oncology',
  'viral-oncolysis',
  'viral-oncolytic-therapy',
  'viral-therapies',
  'viral-therapy',
  'viral-therapy-research',
  'zika-infected-cells',
  'zika-infection',
]
