tags_must_have = [
  'azov-brigade',
  'dmitry-peskov',
  'neo-nazism',
  'russia',
  'ukraine',
  'us-foreign-policy',
]

tags_should_have = [
  'armed-conflict',
  'azov-brigade-history',
  'azov-brigade-operations',
  'civil-military-relations',
  'combat-capabilities',
  'combat-readiness',
  'conflict-and-peace',
  'conflict-management',
  'conflict-studies',
  'counter-terrorism',
  'counterterrorism',
  'defense',
  'defense-acquisition',
  'defense-and-foreign-policy',
  'defense-and-security',
  'defense-cooperation',
  'defense-industry',
  'defense-initiatives',
  'defense-of-mariupol',
  'defense-policy',
  'diplomatic-relations',
  'dmitry-peskov-statements',
  'eastern-europe-conflicts',
  'eastern-european-conflicts',
  'eastern-ukraine',
  'ethics',
  'ethnic-conflict',
  'ethnic-nationalism',
  'ethnic-studies',
  'extremism',
  'extremism-and-terrorism',
  'extremism-in-society',
  'extremism-in-ukraine',
  'extremism-research',
  'extremism-studies',
  'extremist-groups',
  'far-right-extremism',
  'far-right-groups',
  'far-right-movements',
  'force-structure',
  'foreign-affairs',
  'foreign-aid',
  'foreign-intervention',
  'foreign-policy',
  'foreign-policy-implications',
  'foreign-relations',
  'foreign-relations-theory',
  'founders-of-azov-brigade',
  'geopolitical-conflicts',
  'geopolitical-strategies',
  'geopolitical-strategy',
  'geopolitical-tensions',
  'geopolitics',
  'global-political-dynamics',
  'global-security',
  'global-security-issues',
  'global-terrorism',
  'history',
  'human-rights',
  'human-rights-and-justice',
  'human-rights-and-security',
  'human-rights-issues',
  'human-rights-law',
  'human-rights-violations',
  'human-rights-violations-claims',
  'human-rights-violations-in-war',
  'human-rights-watch',
  'human-rights-watch-reports',
  'humanitarian-law',
  'infrastructure-of-azov-brigade',
  'intelligence-analysis',
  'international-community',
  'international-conflict',
  'international-development',
  'international-justice',
  'international-law',
  'international-law-and-conflict',
  'international-law-and-ethics',
  'international-military-cooperation',
  'international-relations',
  'international-relations-theory',
  'international-security',
  'law',
  'law-and-justice',
  'law-enforcement',
  'law-of-war',
  'mariupol',
  'military',
  'military-affairs',
  'military-alliances',
  'military-alliances-and-coalitions',
  'military-alliances-in-europe',
  'military-and-politics',
  'military-and-society',
  'military-conflict',
  'military-education',
  'military-engagement',
  'military-ethics',
  'military-ethics-and-law',
  'military-ethics-in-conflict',
  'military-history',
  'military-history-and-ethics',
  'military-history-and-strategy',
  'military-innovation',
  'military-intelligence',
  'military-logistics',
  'military-operations',
  'military-operations-and-strategy',
  'military-operations-in-ukraine',
  'military-organization',
  'military-strategies',
  'military-strategy',
  'military-structure',
  'military-technology',
  'national-defense',
  'national-guard',
  'national-guard-of-ukraine',
  'national-security',
  'national-security-strategies',
  'national-security-strategy',
  'nationalism',
  'nationalism-and-extremism',
  'nationalism-in-eastern-europe',
  'nationalism-in-europe',
  'neo-nazi-accusations',
  'peace-and-conflict-resolution',
  'peace-and-conflict-studies',
  'peacekeeping-operations',
  'political-ideologies',
  'political-ideologies-in-conflict',
  'politics',
  'post-soviet-conflicts',
  'public-policy',
  'regional-stability',
  'russian-accusations',
  'russo-ukrainian-war',
  'security',
  'security-and-defense-policy',
  'security-assistance',
  'security-cooperation',
  'security-dilemmas',
  'security-policy',
  'security-studies',
  'siege-of-mariupol',
  'social-movements',
  'social-sciences',
  'strategic-communications',
  'strategic-studies',
  'terrorism',
  'terrorism-and-extremism',
  'terrorism-studies',
  'terrorist-organizations',
  'ukrainian-armed-forces',
  'ukrainian-government',
  'ukrainian-military-history',
  'ukrainian-military-structure',
  'ukrainian-national-guard',
  'ukrainian-national-guard-structure',
  'ukrainian-nationalism',
  'ukrainian-sovereignty',
  'ukrainian-sovereignty-issues',
  'ultranationalism',
  'united-states',
  'united-states-state-department',
  'us',
  'us-foreign-policy-in-eastern-europe',
  'us-military',
  'us-military-aid',
  'us-state-department',
  'us-state-department-decision',
  'us-state-department-policies',
  'us-state-department-policy',
  'us-ukraine-military-cooperation',
  'us-ukraine-relations',
  'us-weapons',
  'us-weapons-usage',
  'war-studies',
  'weapons-restrictions',
  'weapons-systems',
  'weapons-usage-restrictions'
]
