tags_must_have = []
tags_should_have = [
  'academic-article',
  'academic-journals',
  'academic-publishing',
  'academic-research',
  'algorithm-description',
  'algorithm-design',
  'algorithm-development',
  'algorithm-optimization',
  'algorithmic-bias',
  'algorithmic-efficiency',
  'algorithmic-innovation',
  'algorithmic-research',
  'algorithmic-research-trends',
  'algorithmic-strategies',
  'animals-with-attributes',
  'applied-mathematics',
  'artificial-intelligence',
  'artificial-intelligence-applications',
  'artificial-intelligence-methodologies',
  'benchmark-datasets',
  'big-data-analytics',
  'bioinformatics',
  'classification-techniques',
  'computational-complexity',
  'computational-efficiency',
  'computational-intelligence',
  'computational-intelligence-applications',
  'computational-methods',
  'computational-statistics',
  'computational-theories',
  'computational-theory',
  'computer-science',
  'cross-validation',
  'data-analysis',
  'data-analysis-report',
  'data-analytics',
  'data-analytics-methods',
  'data-attributes',
  'data-augmentation',
  'data-driven-decision-making',
  'data-driven-research',
  'data-governance',
  'data-heterogeneity',
  'data-libraries',
  'data-mining',
  'data-repositories',
  'data-science',
  'data-science-techniques',
  'data-sets',
  'deep-learning',
  'ensemble-learning',
  'experimental-design',
  'experimental-results',
  'feature-extraction',
  'feature-selection',
  'github',
  'heteroscedastic-noise',
  'hyperparameter-tuning',
  'hyperplane-construction',
  'information-systems',
  'information-technology',
  'information-theory',
  'keel-dataset',
  'kernel-generated-surfaces',
  'kernel-methods',
  'knowledge-management',
  'latent-information',
  'learning-algorithms',
  'learning-tasks',
  'machine-learning',
  'machine-learning-advancements',
  'machine-learning-applications',
  'machine-learning-research',
  'mathematics',
  'matrix-inversion',
  'methodological-approach',
  'model-comparison',
  'model-comparison-study',
  'model-complexity',
  'model-evaluation',
  'model-implementation',
  'model-training',
  'mtanveer1',
  'multiview-learning',
  'mvtpmsvm',
  'mvtsvm',
  'noise-robustness',
  'noise-structure',
  'numerical-methods',
  'open-access',
  'open-source-project',
  'open-source-software',
  'optimization-problems',
  'optimization-theory',
  'parameter-estimation',
  'parametric-hyperplanes',
  'parametric-margin',
  'pattern-recognition',
  'performance-evaluation',
  'performance-metrics',
  'predictive-modeling',
  'quantitative-analysis',
  'quantitative-research',
  'research-and-development',
  'research-and-innovation',
  'research-impact',
  'research-implications',
  'research-methodology',
  'research-paper',
  'research-summary',
  'scholarly-communication',
  'scientific-communication',
  'scientific-method',
  'scientific-publications',
  'scientific-study',
  'software-development',
  'software-documentation',
  'software-engineering',
  'statistical-analyses',
  'statistical-analysis',
  'statistical-analysis-report',
  'statistical-approaches',
  'statistical-computing',
  'statistical-learning',
  'statistical-learning-theory',
  'statistical-modeling',
  'statistical-software',
  'statistics',
  'supervised-learning',
  'support-vector-machines',
  'synthetic-datasets',
  'theoretical-and-applied-research',
  'theoretical-computer-science',
  'theoretical-contributions',
  'theoretical-foundations',
  'theoretical-paper',
  'twin-parametric-margin',
  'twin-support-vector-machines',
  'uci-dataset']
