tags_must_have = []
tags_should_have = [
  'academic-article',
  'air-pollution',
  'air-pollution-modeling',
  'air-quality-modeling',
  'algorithm-development',
  'algorithm-optimization',
  'algorithmic-design',
  'algorithmic-implementation',
  'algorithmic-optimization',
  'algorithmic-research',
  'analytical-methodology',
  'analytical-methods',
  'analytical-techniques',
  'applied-mathematics',
  'applied-research',
  'applied-research-methods',
  'applied-statistics',
  'approximation-accuracy',
  'approximation-techniques',
  'bioinformatics',
  'bioinformatics-research',
  'bioinformatics-techniques',
  'computational-approaches',
  'computational-biology',
  'computational-methodology',
  'computational-methods',
  'computational-research',
  'computational-science',
  'computational-statistics',
  'correlation-analysis',
  'data-analysis',
  'data-analysis-methods',
  'data-analytics',
  'data-driven-approaches',
  'data-driven-methodologies',
  'data-interpretation',
  'data-interpretation-methods',
  'data-reduction-techniques',
  'data-representation',
  'data-representation-techniques',
  'data-science',
  'data-science-methods',
  'data-science-research',
  'data-simulation',
  'data-visualization',
  'data-visualization-techniques',
  'dimension-reduction',
  'dimension-reduction-algorithms',
  'environmental-data',
  'environmental-modeling',
  'environmental-research',
  'environmental-science',
  'environmental-science-research',
  'evaluation-metrics',
  'geospatial-analysis',
  'geostatistics',
  'healthcare-analytics',
  'lower-dimensional-representation',
  'machine-learning',
  'machine-learning-algorithms',
  'machine-learning-research',
  'methodological-advancements',
  'methodological-approach',
  'methodological-research',
  'model-evaluation',
  'model-performance',
  'model-utility',
  'modeling-frameworks',
  'modeling-strategies',
  'modeling-techniques',
  'multivariate-analysis',
  'multivariate-statistics',
  'performance-evaluation',
  'prediction-accuracy',
  'predictive-analytics',
  'principal-component-analysis',
  'public-health',
  'public-health-research',
  'quantitative-analysis',
  'quantitative-analysis-methods',
  'quantitative-methodology',
  'quantitative-methods',
  'quantitative-research',
  'research-design',
  'research-methodology',
  'research-paper',
  'simulation-methods',
  'simulation-studies',
  'spatial-analysis',
  'spatial-analytics',
  'spatial-analytics-methods',
  'spatial-correlation',
  'spatial-correlation-analysis',
  'spatial-data',
  'spatial-modeling',
  'spatial-transcriptomics',
  'statistical-approach',
  'statistical-approaches',
  'statistical-approximation',
  'statistical-inference',
  'statistical-methodology',
  'statistical-modeling',
  'statistical-research',
  'statistical-techniques',
  'statistical-theory',
  'statistical-visualization',
  'statistics',
  'theoretical-framework',
  'theoretical-frameworks',
  'transcriptomics',
  'transcriptomics-analysis']
