tags_must_have = [
  'eastern-us',
  'electricity-outages',
  'kilgore',
  'meteorology',
  'natural-disasters',
  'property-damage',
  'texas',
  'tyler',
]

tags_should_have = [
  'central-us',
  'city-of-kilgore',
  'city-of-tyler',
  'civil-engineering',
  'climate-events',
  'climate-related-events',
  'disaster-affected-areas',
  'disaster-management',
  'disaster-recovery',
  'disaster-relief',
  'disaster-response',
  'electricity-restoration',
  'emergency-preparedness',
  'emergency-response',
  'energy-consumption',
  'energy-disruption',
  'energy-disruptions',
  'energy-distribution',
  'energy-grid',
  'energy-infrastructure',
  'energy-issues',
  'energy-management',
  'energy-sector',
  'energy-supply',
  'energy-supply-challenges',
  'energy-systems',
  'environmental-disasters',
  'environmental-hazards',
  'environmental-impact',
  'environmental-impacts',
  'environmental-safety',
  'government-response',
  'hazardous-driving-conditions',
  'heavy-rains',
  'high-winds',
  'hurricane-impacts',
  'infrastructure-damage',
  'infrastructure-failure',
  'infrastructure-failures',
  'kilgore-texas',
  'local-news',
  'local-reports',
  'michael-barera',
  'natural-hazards',
  'northern-corridor',
  'power-distribution',
  'power-grid-areas',
  'power-outages',
  'power-restoration',
  'regional-impacts',
  'risk-assessment',
  'risk-management',
  'roadway-clearing',
  'roadway-safety',
  'rural-areas',
  'severe-storms',
  'severe-weather',
  'smith-county',
  'smith-county-texas',
  'southern-tyler',
  'storm-damage',
  'storm-preparedness',
  'storm-recovery-efforts',
  'storm-timing',
  'storm-tracking',
  'sustainability',
  'sustainability-studies',
  'tornado-activity',
  'tornado-impacts',
  'traffic-conditions',
  'transportation',
  'transportation-planning',
  'transportation-safety',
  'transportation-systems',
  'tree-falls',
  'tree-removal',
  'tyler-area',
  'tyler-texas',
  'united-states',
  'urban-areas',
  'urban-development',
  'urban-impacts',
  'urban-infrastructure',
  'urban-planning',
  'urban-resilience',
  'urban-resilience-strategies',
  'urban-safety',
  'urban-studies',
  'weather-advisories',
  'weather-affected-areas',
  'weather-agencies',
  'weather-conditions',
  'weather-events',
  'weather-forecasting',
  'weather-impacts',
  'weather-phenomena',
  'weather-preparedness',
  'weather-systems'
]
