name: release python
on:
  workflow_dispatch:
    inputs:
      bump_version:
        type: choice
        description: "bump version"
        default: minor
        options:
        # major version bumps do only manually
        - minor
        - patch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:

  # TODO: uncomment
  # run-checks:
  #   uses: ./.github/workflows/code-checks.yaml
  #   with:
  #     branch_ref: ${{ github.ref }}

  release-python:
    # TODO: uncomment
    # needs: run-checks
    timeout-minutes: 20
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Prepare Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: Install poetry
        run: pip install poetry

      - name: prepare release
        run: ./bin/release-python.sh ${{ github.event.inputs.bump_version }}

      # TODO: commit
      # TODO: create tag
      # TODO: upload
