name: release
on:
  workflow_dispatch:
    inputs:
      bump_version:
        type: choice
        description: "bump version"
        default: minor
        options:
        # major version bumps do only manually
        - minor
        - patch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:

  run-checks:
    uses: ./.github/workflows/code-checks.yaml
    with:
      branch_ref: ${{ github.ref }}

  prepare-release:
    needs: run-checks
    uses: ./.github/workflows/prepare-release.yaml
    with:
      branch_ref: ${{ github.ref }}
      bump_version: ${{ github.event.inputs.bump_version }}

  upload-release:
    needs: prepare-release
    uses: ./.github/workflows/upload-release.yaml
    with:
      branch_ref: ${{ github.ref }}
