name: upload-release
on:
  workflow_dispatch:

  push:
    tags:
      - 'release-*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:

  upload_release:
    timeout-minutes: 20
    runs-on: ubuntu-22.04
    environment: release
    permissions:
      contents: write
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Prepare Node
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Install poetry
        run: pip install poetry

      - name: Prepare Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          cache: 'poetry'

      - name: build python package
        working-directory: ffun
        run: poetry build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.9
        with:
          packages-dir: ffun/dist/

      - name: Publish package distributions to NPM
        working-directory: site
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_SECRET }}
